# Generated by Django 5.2.11 on 2026-03-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(help_text='Unique identifier (e.g., ZoomJetPackSafetyAdvisory)', max_length=100, unique=True)),
                ('description', models.CharField(help_text='Human-readable description', max_length=200)),
                ('file', models.FileField(help_text='PDF file', upload_to='document_templates/static')),
                ('tagging_type', models.CharField(default='pdf_fields', help_text="How the document is tagged; 'pdf_fields' for PDF form fields", max_length=50)),
                ('tagging_data', models.JSONField(default=list, help_text='Array of form-field definitions: tag_name, field_type, member_info_number, etc.')),
            ],
            options={
                'verbose_name': 'Static document template',
                'verbose_name_plural': 'Static document templates',
            },
        ),
    ]
