# Generated by Django 5.2.11 on 2026-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctemplates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(help_text='Unique identifier (e.g., ZoomJetPackLease)', max_length=100, unique=True)),
                ('description', models.CharField(help_text='Human-readable description', max_length=200)),
                ('file', models.FileField(help_text='HTML template file', upload_to='document_templates/dynamic')),
                ('tagging_type', models.CharField(default='text_tagging', help_text="How the document is tagged; 'text_tagging' for SIGNiX anchor text", max_length=50)),
                ('tagging_data', models.JSONField(default=list, help_text='Array of text-tagging field definitions: tag_name, field_type, anchor_text, bounding_box, etc.')),
                ('mapping', models.JSONField(default=dict, help_text='Maps template variable names to {source, transform?, ...} per DESIGN-DOCS')),
            ],
            options={
                'verbose_name': 'Dynamic document template',
                'verbose_name_plural': 'Dynamic document templates',
            },
        ),
    ]
