# Generated by Django 5.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("deals", "0002_add_dealtype_and_deal_type"),
        ("doctemplates", "0002_add_dynamicdocumenttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSetTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, help_text="Display name; if blank, deal type name is used", max_length=200)),
                (
                    "deal_type",
                    models.ForeignKey(
                        help_text="Deal Type this set applies to (one set per type)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deals.dealtype",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document set template",
                "verbose_name_plural": "Document set templates",
                "ordering": ["deal_type__name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSetTemplateItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(help_text="1-based order within the set")),
                ("object_id", models.PositiveIntegerField(help_text="PK of the template")),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="StaticDocumentTemplate or DynamicDocumentTemplate",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "document_set_template",
                    models.ForeignKey(
                        help_text="Parent document set template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="doctemplates.documentsettemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document set template item",
                "verbose_name_plural": "Document set template items",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentsettemplateitem",
            constraint=models.UniqueConstraint(
                fields=("document_set_template", "order"),
                name="doctemplates_dstitem_unique_order_per_template",
            ),
        ),
    ]
