# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctemplates", "0003_add_docsettemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticdocumenttemplate",
            name="signature_field_names",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Optional map of member_info_number to PDF AcroForm field name when tag_name is not set in tagging_data. E.g. {"1": "LessorSignature", "2": "LesseeSignature"}. If empty, defaults Lessor/Lessee are used.',
            ),
        ),
    ]
