# Generated by Django 5.2.11 on 2026-03-03 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('deals', '0002_add_dealtype_and_deal_type'),
        ('doctemplates', '0003_add_docsettemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.ForeignKey(help_text='Deal this document set belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='document_sets', to='deals.deal')),
                ('document_set_template', models.ForeignKey(blank=True, help_text='Template used to create this set; SET_NULL if template is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctemplates.documentsettemplate')),
            ],
            options={
                'verbose_name': 'Document set',
                'verbose_name_plural': 'Document sets',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-based order within the set')),
                ('object_id', models.PositiveIntegerField(help_text='PK of the source template')),
                ('template_type', models.CharField(help_text="Denormalized: 'static' or 'dynamic'", max_length=20)),
                ('content_type', models.ForeignKey(help_text='StaticDocumentTemplate or DynamicDocumentTemplate', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('document_set', models.ForeignKey(help_text='Parent document set', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='documents.documentset')),
            ],
            options={
                'verbose_name': 'Document instance',
                'verbose_name_plural': 'Document instances',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInstanceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version (1, 2, 3, …)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(help_text='e.g. Draft, Submitted to SIGNiX, Final', max_length=50)),
                ('file', models.FileField(blank=True, help_text='PDF file', upload_to='documents/%Y/%m/')),
                ('document_instance', models.ForeignKey(help_text='Parent document instance', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.documentinstance')),
            ],
            options={
                'verbose_name': 'Document instance version',
                'verbose_name_plural': 'Document instance versions',
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('document_instance', 'version_number'), name='documents_docver_unique_version_per_instance')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentinstance',
            constraint=models.UniqueConstraint(fields=('document_set', 'order'), name='documents_docinst_unique_order_per_set'),
        ),
    ]
