# Generated by Django 5.2.11 on 2026-03-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseofficerprofile',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'Eastern (America/New_York)'), ('America/Chicago', 'Central (America/Chicago)'), ('America/Denver', 'Mountain (America/Denver)'), ('America/Los_Angeles', 'Pacific (America/Los_Angeles)'), ('America/Phoenix', 'Arizona (America/Phoenix)'), ('UTC', 'UTC')], default='America/New_York', help_text='Timezone for displaying dates and times in the app (e.g. Eastern).', max_length=63),
        ),
    ]
