"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-43i3ipdw_!i2@hafc%h7ko&%j%@60+vt)9!ui0s^k4m0k3)mlt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.app",
    ".ngrok-free.dev",
    ".ngrok.io",
]

# Required when using ngrok (or other HTTPS proxy): login and other POSTs send Origin
# matching the tunnel URL; Django's CSRF check requires it to be trusted.
# Replace with your ngrok domain if you use a different account/machine (see PLAN-NGROK.md).
CSRF_TRUSTED_ORIGINS = [
    "https://unreproachable-draftily-shanelle.ngrok-free.dev",
    "http://unreproachable-draftily-shanelle.ngrok-free.dev",
]

# Base URL used for image URLs when generating PDFs (dynamic templates). wkhtmltopdf
# runs on the server and must fetch image URLs; if the user triggers generation via
# ngrok, request.build_absolute_uri() would give an ngrok URL that wkhtmltopdf may
# not reach reliably. Use a local URL so the generated PDF always has working images.
PDF_IMAGE_BASE_URL = "http://127.0.0.1:8000"


# Application definition
# Jazzmin must be listed first so it can override admin templates/site.
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.users",
    "apps.vehicles",
    "apps.contacts",
    "apps.deals",
    "apps.schema",
    "apps.images",
    "apps.doctemplates",
    "apps.documents",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.users.middleware.ProfileTimezoneMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Display datetimes in this zone when no user timezone is active (anonymous or fallback).
# Per-user timezone is set on the profile and activated by ProfileTimezoneMiddleware.
TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (user uploads, e.g. images for document templates)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth: where to send users for login and after login/logout (Batch 2 will add views).
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/profile/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Jazzmin: admin theme. custom_links = sidebar only.
# Person icon in top nav: overridden in templates/admin/base.html to link directly to /profile/.
JAZZMIN_SETTINGS = {
    "site_title": "Vehicle Leasing",
    "site_header": "Vehicle Leasing",
    "site_brand": "Vehicle Leasing",
    "custom_links": {
        "main": [
            {"name": "Back to app", "url": "/profile/", "icon": "fas fa-arrow-left"},
            {"name": "Vehicles", "url": "/vehicles/", "icon": "fas fa-truck"},
            {"name": "Contacts", "url": "/contacts/", "icon": "fas fa-users"},
            {"name": "Deals", "url": "/deals/", "icon": "fas fa-file-contract"},
            {"name": "Images", "url": "/images/", "icon": "fas fa-image"},
            {"name": "Admin", "url": "/admin/", "icon": "fas fa-cog"},
        ],
    },
}
JAZZMIN_UI_TWEAKS = {}
