# Generated by Django 5.2.11 on 2026-02-20 16:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField()),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_period', models.CharField(default='month', max_length=20)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('governing_law', models.CharField(default='Delaware', max_length=100)),
                ('contacts', models.ManyToManyField(blank=True, related_name='deals', to='contacts.contact')),
                ('lease_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='deals', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-date_entered', '-id'],
            },
        ),
    ]
