# Generated by Django 5.2.11 on 2026-02-27 14:24

import django.db.models.deletion
from django.db import migrations, models


def create_default_deal_type(apps, schema_editor):
    """Create the default Deal Type 'Lease - Single Signer'."""
    DealType = apps.get_model("deals", "DealType")
    DealType.objects.get_or_create(name="Lease - Single Signer")


def backfill_deal_type(apps, schema_editor):
    """Set deal_type for any Deal with null deal_type."""
    Deal = apps.get_model("deals", "Deal")
    DealType = apps.get_model("deals", "DealType")
    default_type = DealType.objects.get(name="Lease - Single Signer")
    Deal.objects.filter(deal_type__isnull=True).update(deal_type=default_type)


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Deal Type',
                'verbose_name_plural': 'Deal Types',
            },
        ),
        migrations.RunPython(create_default_deal_type, migrations.RunPython.noop),
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.dealtype'),
        ),
        migrations.RunPython(backfill_deal_type, migrations.RunPython.noop),
    ]
