# Generated by Django 5.2.11 on 2026-03-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_add_dealtype_and_deal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('workgroup', models.CharField(blank=True, max_length=255)),
                ('demo_only', models.BooleanField(default=True)),
                ('delete_documents_after_days', models.PositiveIntegerField(default=60)),
                ('default_email_content', models.TextField(default='Your documents for the Sample Application are available online for viewing and signing.')),
                ('submitter_first_name', models.CharField(blank=True, max_length=150)),
                ('submitter_middle_name', models.CharField(blank=True, max_length=150)),
                ('submitter_last_name', models.CharField(blank=True, max_length=150)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'SIGNiX configuration',
                'verbose_name_plural': 'SIGNiX configurations',
            },
        ),
    ]
