# Generated by Django 5.2.11 on 2026-03-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_add_signix_config'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signix_document_set_id', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=36)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Suspended', 'Suspended'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=50)),
                ('first_signing_url', models.URLField(blank=True, max_length=512)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_transactions', to='deals.deal')),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentset')),
            ],
            options={
                'verbose_name': 'Signature transaction',
                'verbose_name_plural': 'Signature transactions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
