# Generated by Django 5.2.11 on 2026-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_add_signature_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='signer_authentication',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='signer_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
